---
require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  NewCops: enable

Layout/LineLength:
  Max: 120
  Exclude:
  - Gemfile

Metrics/BlockLength:
  Enabled: false

Performance/TimesMap:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

Style/Documentation:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
