---
require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  NewCops: enable

Layout/LineLength:
  Max: 120
  Exclude:
  - Gemfile

Metrics/BlockLength:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false

Style/Documentation:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
